### ISSUE TITLE
Fix full stack workflow on all containers

### ISSUE THREAD

**Issue by afeefghannam89** [NETWAYS/ansible-collection-elasticstack#194]
Full stack work flow does not work as expected on some containers. We should fix this or remove these containers from testing.

**Comment by widhalmt** [comment]
Do you have a list which work and which won't? I tried to focus on Ubuntu 22.04 LTS and Rocky 8 to reflect what I see most at customers.

**Comment by afeefghannam89** [comment]
Rocky9 I have fixed and centos7 I removed from the tests. The rest was only timeout.

**Comment by dnssmr** [comment]
Is the issue still an issue or did you fix it? @afeefghannam89

**Comment by afeefghannam89** [comment]
@dnssmr it is fixed but not merged yet. The fix is in this branch [fix/pipelines](https://github.com/NETWAYS/ansible-collection-elasticstack/tree/fix/pipelines)

**Comment by widhalmt** [comment]
@afeefghannam89 you told me to ignore this branch. ;-) Should we merge it now?

**Comment by afeefghannam89** [comment]
@widhalmt I meant another one. This branch [fix/pipelines](https://github.com/NETWAYS/ansible-collection-elasticstack/tree/fix/pipelines) is ready to review :) I have closed the PR, which I meant to ignore.
